#!/bin/sh -e
#
# check_tcp_syn:   TCP half-open check script for keepalived's MISC_CHECK
#
# Authors:         Ilya Voronin <ivoronin@jet.msk.su>
#
# Tested with:     Nmap 6.40 and xmllint 20901
#
# Arguments:       ADDR - normalized (w/o leading zeroes) IPv4 address
#                  PORT - normalized (w/o leading zeroes) TCP port
#
#                  This program is free software; you can redistribute it and/or
#                  modify it under the terms of the GNU General Public License
#                  as published by the Free Software Foundation; either version
#                  2 of the License, or (at your option) any later version.
#

[ "$#" -ne "2" ] && echo "Usage: check_tcp_syn ADDR PORT" 1>&2 && exit 1
XPATH="string(/nmaprun/host[address/@addr='$1']/ports/port[@portid='$2']/state/@state)"
STATE="$(nmap -n -sS -Pn -oX - -p "$2" "$1" | xmllint --xpath "${XPATH}" -)"
[ "${STATE}" == "open" ] && exit 0 || exit 1
