#!/bin/sh
#
# check_tcp_syn:   TCP half-open check script for keepalived's MISC_CHECK
#
# Authors:         Ilya Voronin <ivoronin@jet.msk.su>
#
# Tested with:     Nmap 6.40 and xmllint 20901
#
# Arguments:       ADDR - normalized (w/o leading zeroes) IPv4 address
#                  PORT - normalized (w/o leading zeroes) TCP port
#
#                  This program is free software; you can redistribute it and/or
#                  modify it under the terms of the GNU General Public License
#                  as published by the Free Software Foundation; either version
#                  2 of the License, or (at your option) any later version.
#

set -e

if [ "$#" -ne "2" ]; then
    echo "Usage: check_tcp_syn ADDR PORT" 1>&2
    exit 1
fi

ADDR="$1"
PORT="$2"

NMAP_CMD="nmap -n -sS -Pn -oX - -p ${PORT} ${ADDR}"
XPATH_EXPR="string(/nmaprun/host[address/@addr='${ADDR}']/ports/port[@portid='${PORT}']/state/@state)"
XMLLINT_CMD="xmllint --xpath ${XPATH_EXPR} -"

STATE="$(${NMAP_CMD} | ${XMLLINT_CMD})"

if [ "$STATE" == "open" ]; then
    exit 0
else
    exit 1
fi
